services:
  redis:
    container_name: mint-redis
    image: redis:8.4-alpine
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - mint-redis-data:/data

volumes:
  mint-redis-data: