services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mint-server:
    container_name: mint-api
    env_file:
      - .env.api
    build: ./mint-server
    ports:
      - ${API_PORT}:3000
    environment:
      DATABASE_URL: "postgres://postgres:example@db:5432/postgres"
    volumes:
      - ./mint-server:/app
      - mint-server-node-modules:/app/node_modules

    depends_on:
      - db
      - adminer
    restart: always

  mint-ws-runners:
    env_file:
      - .env.ws
    build: ./mint-ws-runners
    ports:
      - ${WS_PORT}:3000
    volumes:
      - ./mint-ws-runners:/app
    restart: always

  mint-administration:
    platform: linux/amd64
    env_file:
      - .env.administration
    # platform: linux/amd64
    build: ./mint-administration
    ports:
      - ${ADMINISTRATION_PORT}:5173
    volumes:
      - ./mint-administration:/app
      - mint-admin-node-modules:/app/node_modules
    restart: always

volumes:
  mint-admin-node-modules:
  mint-server-node-modules: