DROP TABLE "user_profiles" CASCADE;--> statement-breakpoint
DROP TABLE "users" CASCADE;--> statement-breakpoint
DROP TABLE "visitors" CASCADE;--> statement-breakpoint
DROP TABLE "event_campaigns" CASCADE;--> statement-breakpoint
DROP TABLE "events" CASCADE;--> statement-breakpoint
DROP TABLE "organizations__groups" CASCADE;--> statement-breakpoint
DROP TABLE "organizations" CASCADE;--> statement-breakpoint
DROP TABLE "sponsors__events" CASCADE;--> statement-breakpoint
DROP TABLE "sponsors__organizations" CASCADE;--> statement-breakpoint
DROP TABLE "sponsors__user_profiles" CASCADE;--> statement-breakpoint
DROP TABLE "sponsors" CASCADE;--> statement-breakpoint
DROP TABLE "race_positions" CASCADE;--> statement-breakpoint
DROP TABLE "race_start_waves" CASCADE;--> statement-breakpoint
DROP TABLE "races" CASCADE;--> statement-breakpoint
DROP TABLE "registrations" CASCADE;--> statement-breakpoint
DROP TABLE "time_barriers" CASCADE;--> statement-breakpoint
DROP TABLE "track_segments" CASCADE;--> statement-breakpoint
DROP TABLE "tracks" CASCADE;--> statement-breakpoint
DROP TABLE "groups__permissions" CASCADE;--> statement-breakpoint
DROP TABLE "groups__roles" CASCADE;--> statement-breakpoint
DROP TABLE "groups__user_profiles" CASCADE;--> statement-breakpoint
DROP TABLE "groups" CASCADE;--> statement-breakpoint
DROP TABLE "permissions" CASCADE;--> statement-breakpoint
DROP TABLE "roles__permissions" CASCADE;--> statement-breakpoint
DROP TABLE "roles" CASCADE;--> statement-breakpoint
DROP TABLE "countries" CASCADE;--> statement-breakpoint
DROP TABLE "languages" CASCADE;--> statement-breakpoint
DROP TABLE "translations" CASCADE;--> statement-breakpoint
DROP TABLE "media_contexts" CASCADE;--> statement-breakpoint
DROP TABLE "media_formats" CASCADE;--> statement-breakpoint
DROP TABLE "media_types" CASCADE;--> statement-breakpoint
DROP TABLE "medias" CASCADE;--> statement-breakpoint
DROP TABLE "custom_settings" CASCADE;--> statement-breakpoint
DROP TABLE "setting_categories" CASCADE;--> statement-breakpoint
DROP TABLE "setting_keys" CASCADE;--> statement-breakpoint
DROP TABLE "setting_multiple_options" CASCADE;--> statement-breakpoint
DROP TABLE "setting_selected_options" CASCADE;--> statement-breakpoint
DROP TABLE "setting_types" CASCADE;--> statement-breakpoint
DROP TABLE "profile_links" CASCADE;--> statement-breakpoint
DROP TABLE "social_platforms" CASCADE;--> statement-breakpoint
DROP TABLE "badge_levels" CASCADE;--> statement-breakpoint
DROP TABLE "badge_progressions" CASCADE;--> statement-breakpoint
DROP TABLE "badges" CASCADE;--> statement-breakpoint
DROP TABLE "action_levels" CASCADE;--> statement-breakpoint
DROP TABLE "race_discipline_categories" CASCADE;--> statement-breakpoint
DROP TABLE "race_discipline" CASCADE;--> statement-breakpoint
DROP TABLE "standard_distances" CASCADE;