server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  # Optionnel : pour avoir des logs plus lisibles
  access_log /dev/stdout;
  error_log /dev/stderr;
}
