name: Build & Deploy Mint API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Push Docker image, Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t charleschrismann/mint-api:latest \
            --push ./mint-server/

      - name: SSH and Deploy on Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd mint/
            echo "Pull de la dernière image..."
            docker compose -f docker-compose.prod.yml pull mint-api

            echo "Recréation et relancement du service..."
            docker compose -f docker-compose.prod.yml up -d mint-api
